spring.application.name=student-management

spring.datasource.url=jdbcpostgresql://student_user:af7qUU7ByKs89Xu3dX38fWtXr7vKQYl1@dpg-d9jms0km0tmc73bauqo0-a.singapore-postgres.render.com/student_db_typ5
spring.datasource.username=student_user
spring.datasource.password=af7qUU7ByKs89Xu3dX38fWtXr7vKQYl1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
